import { SearchMode, Settings, VoiceName } from '../types';

// Mock implementation - replace with actual Gemini API calls
export async function generateNarrative(
  query: string,
  mode: SearchMode,
  settings: Settings,
  _chatHistory: Array<{ role: string; content: string }>
): Promise<string> {
  // reference _chatHistory to avoid unused variable lint
  void _chatHistory;
  // Simulate API call with delay
  await new Promise(resolve => setTimeout(resolve, 1000));

  const modeText = mode === SearchMode.BOOK ? 'book' : mode === SearchMode.CASE_STUDY ? 'case study' : 'ask';
  return `Here is a ${settings.narrationType.toLowerCase()} narration about "${query}" in ${modeText} format. 
This is a placeholder narrative. In production, this would be generated by Google Gemini API based on the search query.
The narration would be tailored to your language preference (${settings.language}) and adapted to the ${settings.narrationTime}-minute duration you specified.
You can continue the conversation to explore more perspectives or ask follow-up questions.`;
}

export async function generateSpeech(_text: string, _voiceType: VoiceName): Promise<string> {
  // Mock implementation - replace with actual text-to-speech API
  // reference unused params to avoid lint
  void _text;
  void _voiceType;
  await new Promise(resolve => setTimeout(resolve, 500));
  
  // Return empty string for now - in production, this would be a base64 encoded audio
  return '';
}

export function decodeAudio(base64: string): Uint8Array {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

export async function getAudioBuffer(
  data: Uint8Array,
  audioContext: AudioContext
): Promise<AudioBuffer> {
  const arrayBuffer = data.buffer as ArrayBuffer;
  return audioContext.decodeAudioData(arrayBuffer);
}
